meta_product_name: "Comp'Arts"
meta_title: "Comp'Arts - La plateforme artistique de Bordeaux"
meta_description: "Comp’arts est un site communautaire participatif pour le développement de l’univers artistique bordelais. "
#meta_image: "image.jpg"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@Comparts_bdx"              # indispensable pour les Twitter Cards